import {
  Bug,
  Car,
  CheckCircle2,
  Clock,
  Droplets,
  Flame,
  Hammer,
  Home,
  Key,
  Leaf,
  PaintRoller,
  Scissors,
  Search,
  Settings,
  Shield,
  Sparkles,
  Thermometer,
  Truck,
  Waves,
  Wind,
  Wrench,
  Zap,
  type LucideIcon,
} from 'lucide-react'

export const SERVICE_ICONS: Record<string, LucideIcon> = {
  wrench: Wrench,
  droplets: Droplets,
  waves: Waves,
  flame: Flame,
  zap: Zap,
  thermometer: Thermometer,
  wind: Wind,
  hammer: Hammer,
  home: Home,
  shield: Shield,
  sparkles: Sparkles,
  paintRoller: PaintRoller,
  leaf: Leaf,
  bug: Bug,
  car: Car,
  scissors: Scissors,
  key: Key,
  search: Search,
  truck: Truck,
  settings: Settings,
  clock: Clock,
  checkCircle: CheckCircle2,
}

export const SERVICE_ICON_OPTIONS = [
  { label: 'Wrench (general repair)', value: 'wrench' },
  { label: 'Droplets (plumbing/leaks)', value: 'droplets' },
  { label: 'Waves (drainage/flow)', value: 'waves' },
  { label: 'Flame (heating/hot water)', value: 'flame' },
  { label: 'Zap (electrical)', value: 'zap' },
  { label: 'Thermometer (climate/HVAC)', value: 'thermometer' },
  { label: 'Wind (air/ventilation)', value: 'wind' },
  { label: 'Hammer (construction)', value: 'hammer' },
  { label: 'Home (general home services)', value: 'home' },
  { label: 'Shield (safety/warranty)', value: 'shield' },
  { label: 'Sparkles (cleaning)', value: 'sparkles' },
  { label: 'Paint Roller (painting)', value: 'paintRoller' },
  { label: 'Leaf (landscaping/eco)', value: 'leaf' },
  { label: 'Bug (pest control)', value: 'bug' },
  { label: 'Car (automotive)', value: 'car' },
  { label: 'Scissors (trimming/grooming)', value: 'scissors' },
  { label: 'Key (locksmith/security)', value: 'key' },
  { label: 'Search (inspection/detection)', value: 'search' },
  { label: 'Truck (delivery/moving)', value: 'truck' },
  { label: 'Settings (maintenance)', value: 'settings' },
  { label: 'Clock (24/7/emergency)', value: 'clock' },
  { label: 'Check Circle (quality/guarantee)', value: 'checkCircle' },
]
