/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    services: Service;
    'contact-submissions': ContactSubmission;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    services: ServicesSelect<false> | ServicesSelect<true>;
    'contact-submissions': ContactSubmissionsSelect<false> | ContactSubmissionsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    'company-info': CompanyInfo;
    theme: Theme;
    'site-nav': SiteNav;
    header: Header;
    footer: Footer;
    'home-page': HomePage;
    'about-page': AboutPage;
    'services-page': ServicesPage;
    'contact-page': ContactPage;
    'trust-strip': TrustStrip;
    testimonials: Testimonial;
    'service-area': ServiceArea;
  };
  globalsSelect: {
    'company-info': CompanyInfoSelect<false> | CompanyInfoSelect<true>;
    theme: ThemeSelect<false> | ThemeSelect<true>;
    'site-nav': SiteNavSelect<false> | SiteNavSelect<true>;
    header: HeaderSelect<false> | HeaderSelect<true>;
    footer: FooterSelect<false> | FooterSelect<true>;
    'home-page': HomePageSelect<false> | HomePageSelect<true>;
    'about-page': AboutPageSelect<false> | AboutPageSelect<true>;
    'services-page': ServicesPageSelect<false> | ServicesPageSelect<true>;
    'contact-page': ContactPageSelect<false> | ContactPageSelect<true>;
    'trust-strip': TrustStripSelect<false> | TrustStripSelect<true>;
    testimonials: TestimonialsSelect<false> | TestimonialsSelect<true>;
    'service-area': ServiceAreaSelect<false> | ServiceAreaSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services".
 */
export interface Service {
  id: number;
  title: string;
  /**
   * Used in the URL: /services/[slug]
   */
  slug: string;
  /**
   * SEO description shown in search results and social share previews
   */
  metaDescription?: string | null;
  /**
   * Icon shown on the services grid card
   */
  icon?:
    | (
        | 'wrench'
        | 'droplets'
        | 'waves'
        | 'flame'
        | 'zap'
        | 'thermometer'
        | 'wind'
        | 'hammer'
        | 'home'
        | 'shield'
        | 'sparkles'
        | 'paintRoller'
        | 'leaf'
        | 'bug'
        | 'car'
        | 'scissors'
        | 'key'
        | 'search'
        | 'truck'
        | 'settings'
        | 'clock'
        | 'checkCircle'
      )
    | null;
  heroImage?: (number | null) | Media;
  /**
   * Short description shown on the services grid card and page hero
   */
  subtext?: string | null;
  primaryCta?: {
    label?: string | null;
    href?: string | null;
  };
  /**
   * Long-form body copy for the individual service page
   */
  description: string;
  whatsIncluded?:
    | {
        item: string;
        id?: string | null;
      }[]
    | null;
  relatedServices?: (number | Service)[] | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Submissions from the public contact form
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-submissions".
 */
export interface ContactSubmission {
  id: number;
  name: string;
  phone?: string | null;
  email: string;
  message: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'services';
        value: number | Service;
      } | null)
    | ({
        relationTo: 'contact-submissions';
        value: number | ContactSubmission;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services_select".
 */
export interface ServicesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  metaDescription?: T;
  icon?: T;
  heroImage?: T;
  subtext?: T;
  primaryCta?:
    | T
    | {
        label?: T;
        href?: T;
      };
  description?: T;
  whatsIncluded?:
    | T
    | {
        item?: T;
        id?: T;
      };
  relatedServices?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-submissions_select".
 */
export interface ContactSubmissionsSelect<T extends boolean = true> {
  name?: T;
  phone?: T;
  email?: T;
  message?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * Shared business contact details, used across the Footer and Contact page (including the emergency callout phone number).
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "company-info".
 */
export interface CompanyInfo {
  id: number;
  businessName: string;
  /**
   * Shown in the header in place of the business name text, if uploaded
   */
  logo?: (number | null) | Media;
  /**
   * Short one-line tagline shown under the logo in the footer
   */
  footerTagline?: string | null;
  phone?: string | null;
  email?: string | null;
  /**
   * Always used to geocode the map/service-radius location, regardless of the "Show Address" setting below.
   */
  address?: string | null;
  /**
   * Turn off to hide the address from the Footer and Contact page — useful if it's a home address or one customers shouldn't visit. The map and service radius still work either way.
   */
  showAddress?: boolean | null;
  hours?: string | null;
  /**
   * Radius (in km) drawn as a circle on the Contact page map, centered on the geocoded business address.
   */
  serviceRadiusKm?: number | null;
  /**
   * Auto-geocoded from Address — do not edit directly.
   */
  latitude?: number | null;
  /**
   * Auto-geocoded from Address — do not edit directly.
   */
  longitude?: number | null;
  /**
   * Google Place ID for this business, used to fetch the live review carousel on the homepage. Find it via Google's Place ID Finder (developers.google.com/maps/documentation/places/web-service/place-id) or your Google Business Profile.
   */
  googlePlaceId?: string | null;
  /**
   * Shown in the footer, below the phone and email. Leave any blank to hide that icon.
   */
  socialLinks?: {
    /**
     * Full Facebook page URL
     */
    facebook?: string | null;
    /**
     * Full Instagram profile URL
     */
    instagram?: string | null;
    /**
     * Full X/Twitter profile URL
     */
    x?: string | null;
    /**
     * Full LinkedIn page URL
     */
    linkedin?: string | null;
  };
  /**
   * Shown in the footer bottom bar. Leave either blank to hide that link.
   */
  legalLinks?: {
    privacyPolicyUrl?: string | null;
    termsUrl?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Brand colors for this site. Enter hex codes (e.g. #1a56db). Readable text color on Primary/Accent is calculated automatically.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "theme".
 */
export interface Theme {
  id: number;
  /**
   * Main brand color — solid buttons (Get a Quote, Call Now, etc.), text links, and icon accents like service checkmarks. Text shown on top of it is calculated automatically for contrast.
   */
  primaryColor: string;
  /**
   * Page and card background color. Also blended with the text color to produce the derived border, input outline, and focus ring tones.
   */
  backgroundColor: string;
  /**
   * Header and footer background color (including the mobile dropdown menu). Set this per client to match the background baked into their logo file, so the logo sits cleanly on both — independent of the general page background. Text color on both is calculated automatically for contrast.
   */
  headerBackgroundColor: string;
  /**
   * Main text color. Also blended with the background color to produce derived tones — muted/secondary text, borders, input outlines, and focus rings.
   */
  foregroundColor: string;
  /**
   * Optional override for the text/icon color shown on top of the Primary color. Leave blank to auto-calculate a readable black or white based on Primary Color.
   */
  primaryTextColor?: string | null;
  /**
   * Secondary background — badges/chips, hover backgrounds on nav links and outline buttons, and muted section backgrounds like the final CTA banner.
   */
  accentColor: string;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Nav links shared by both the Header and the Footer.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-nav".
 */
export interface SiteNav {
  id: number;
  navLinks?:
    | {
        label: string;
        page: '/' | '/about' | '/services' | '/contact' | 'custom';
        /**
         * Full URL, shown only when "Custom URL" is selected above
         */
        customUrl?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header".
 */
export interface Header {
  id: number;
  ctaLabel?: string | null;
  ctaHref?: string | null;
  /**
   * Label for the "call" button on the mobile sticky CTA bar
   */
  callButtonLabel?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer".
 */
export interface Footer {
  id: number;
  copyrightText?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home-page".
 */
export interface HomePage {
  id: number;
  /**
   * SEO description shown in search results and social share previews
   */
  metaDescription?: string | null;
  hero: {
    headline: string;
    subtext?: string | null;
    /**
     * Shown alongside the headline on larger screens
     */
    image?: (number | null) | Media;
    primaryCta?: {
      label?: string | null;
      href?: string | null;
    };
  };
  servicesPreview?: {
    heading?: string | null;
    subtext?: string | null;
    /**
     * Shown on the homepage services grid — max 3.
     */
    featuredServices?: (number | Service)[] | null;
    viewAllLabel?: string | null;
    /**
     * Link label shown at the bottom of each service card
     */
    readMoreLabel?: string | null;
  };
  finalCta?: {
    heading?: string | null;
    subtext?: string | null;
    buttonLabel?: string | null;
    buttonHref?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "about-page".
 */
export interface AboutPage {
  id: number;
  /**
   * SEO description shown in search results and social share previews
   */
  metaDescription?: string | null;
  hero: {
    headline: string;
    subtext?: string | null;
    /**
     * Shown alongside the headline on larger screens
     */
    image?: (number | null) | Media;
    primaryCta?: {
      label?: string | null;
      href?: string | null;
    };
  };
  ourStory?: {
    heading?: string | null;
    body?: string | null;
    image?: (number | null) | Media;
  };
  teamGrid?:
    | {
        name: string;
        role?: string | null;
        photo?: (number | null) | Media;
        id?: string | null;
      }[]
    | null;
  finalCta?: {
    heading?: string | null;
    subtext?: string | null;
    buttonLabel?: string | null;
    buttonHref?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services-page".
 */
export interface ServicesPage {
  id: number;
  /**
   * SEO description shown in search results and social share previews
   */
  metaDescription?: string | null;
  hero: {
    headline: string;
    subtext?: string | null;
    /**
     * Shown alongside the headline on larger screens
     */
    image?: (number | null) | Media;
    primaryCta?: {
      label?: string | null;
      href?: string | null;
    };
  };
  howItWorksHeading?: string | null;
  howItWorks?:
    | {
        title: string;
        description?: string | null;
        id?: string | null;
      }[]
    | null;
  faqHeading?: string | null;
  faq?:
    | {
        question: string;
        answer: string;
        id?: string | null;
      }[]
    | null;
  whatsIncludedHeading?: string | null;
  relatedServicesHeading?: string | null;
  finalCta?: {
    heading?: string | null;
    subtext?: string | null;
    buttonLabel?: string | null;
    buttonHref?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-page".
 */
export interface ContactPage {
  id: number;
  /**
   * SEO description shown in search results and social share previews
   */
  metaDescription?: string | null;
  emergencyCallout?: {
    show?: boolean | null;
    message?: string | null;
  };
  pageIntro: {
    headline: string;
    subtext?: string | null;
  };
  contactDetails?: {
    phoneLabel?: string | null;
    emailLabel?: string | null;
    addressLabel?: string | null;
    hoursLabel?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Credential/stat numbers shown on both the homepage and the About page.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "trust-strip".
 */
export interface TrustStrip {
  id: number;
  /**
   * Shown above the stats on the homepage. Not shown on the About page.
   */
  heading?: string | null;
  stats?:
    | {
        label: string;
        value: string;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Homepage "What Our Customers Say" section. The reviews themselves are pulled live from Google using the Place ID set on Company Info.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonials".
 */
export interface Testimonial {
  id: number;
  heading?: string | null;
  /**
   * When on, shows the live Google rating/review count next to the heading, with a link out to the full reviews. Pulled automatically from the Google Place ID on Company Info — nothing to enter manually.
   */
  showGoogleReviewsPill?: boolean | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Homepage "Where We Service" section, also used on the Contact page. Radius, coordinates, and map come from Company Info.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "service-area".
 */
export interface ServiceArea {
  id: number;
  heading?: string | null;
  /**
   * Short area name for service-radius copy, e.g. "Auckland" — shown as "Servicing within {radius}km of {this}".
   */
  label?: string | null;
  /**
   * Suburb/area names shown on the Contact page and homepage service-area section — max 20.
   */
  suburbs?:
    | {
        name: string;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "company-info_select".
 */
export interface CompanyInfoSelect<T extends boolean = true> {
  businessName?: T;
  logo?: T;
  footerTagline?: T;
  phone?: T;
  email?: T;
  address?: T;
  showAddress?: T;
  hours?: T;
  serviceRadiusKm?: T;
  latitude?: T;
  longitude?: T;
  googlePlaceId?: T;
  socialLinks?:
    | T
    | {
        facebook?: T;
        instagram?: T;
        x?: T;
        linkedin?: T;
      };
  legalLinks?:
    | T
    | {
        privacyPolicyUrl?: T;
        termsUrl?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "theme_select".
 */
export interface ThemeSelect<T extends boolean = true> {
  primaryColor?: T;
  backgroundColor?: T;
  headerBackgroundColor?: T;
  foregroundColor?: T;
  primaryTextColor?: T;
  accentColor?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-nav_select".
 */
export interface SiteNavSelect<T extends boolean = true> {
  navLinks?:
    | T
    | {
        label?: T;
        page?: T;
        customUrl?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header_select".
 */
export interface HeaderSelect<T extends boolean = true> {
  ctaLabel?: T;
  ctaHref?: T;
  callButtonLabel?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer_select".
 */
export interface FooterSelect<T extends boolean = true> {
  copyrightText?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home-page_select".
 */
export interface HomePageSelect<T extends boolean = true> {
  metaDescription?: T;
  hero?:
    | T
    | {
        headline?: T;
        subtext?: T;
        image?: T;
        primaryCta?:
          | T
          | {
              label?: T;
              href?: T;
            };
      };
  servicesPreview?:
    | T
    | {
        heading?: T;
        subtext?: T;
        featuredServices?: T;
        viewAllLabel?: T;
        readMoreLabel?: T;
      };
  finalCta?:
    | T
    | {
        heading?: T;
        subtext?: T;
        buttonLabel?: T;
        buttonHref?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "about-page_select".
 */
export interface AboutPageSelect<T extends boolean = true> {
  metaDescription?: T;
  hero?:
    | T
    | {
        headline?: T;
        subtext?: T;
        image?: T;
        primaryCta?:
          | T
          | {
              label?: T;
              href?: T;
            };
      };
  ourStory?:
    | T
    | {
        heading?: T;
        body?: T;
        image?: T;
      };
  teamGrid?:
    | T
    | {
        name?: T;
        role?: T;
        photo?: T;
        id?: T;
      };
  finalCta?:
    | T
    | {
        heading?: T;
        subtext?: T;
        buttonLabel?: T;
        buttonHref?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services-page_select".
 */
export interface ServicesPageSelect<T extends boolean = true> {
  metaDescription?: T;
  hero?:
    | T
    | {
        headline?: T;
        subtext?: T;
        image?: T;
        primaryCta?:
          | T
          | {
              label?: T;
              href?: T;
            };
      };
  howItWorksHeading?: T;
  howItWorks?:
    | T
    | {
        title?: T;
        description?: T;
        id?: T;
      };
  faqHeading?: T;
  faq?:
    | T
    | {
        question?: T;
        answer?: T;
        id?: T;
      };
  whatsIncludedHeading?: T;
  relatedServicesHeading?: T;
  finalCta?:
    | T
    | {
        heading?: T;
        subtext?: T;
        buttonLabel?: T;
        buttonHref?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-page_select".
 */
export interface ContactPageSelect<T extends boolean = true> {
  metaDescription?: T;
  emergencyCallout?:
    | T
    | {
        show?: T;
        message?: T;
      };
  pageIntro?:
    | T
    | {
        headline?: T;
        subtext?: T;
      };
  contactDetails?:
    | T
    | {
        phoneLabel?: T;
        emailLabel?: T;
        addressLabel?: T;
        hoursLabel?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "trust-strip_select".
 */
export interface TrustStripSelect<T extends boolean = true> {
  heading?: T;
  stats?:
    | T
    | {
        label?: T;
        value?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonials_select".
 */
export interface TestimonialsSelect<T extends boolean = true> {
  heading?: T;
  showGoogleReviewsPill?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "service-area_select".
 */
export interface ServiceAreaSelect<T extends boolean = true> {
  heading?: T;
  label?: T;
  suburbs?:
    | T
    | {
        name?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}